export const signupInitialValues = {
    individual: {
        fullName: "",
        email: "",
        age: "",
        aadhaar: "",
        password: "",
        confirmPassword: "",
        receiveRewardsNotifications: false,
        acceptTerms: false
    },

    manufacturer: {
        organizationName: "",
        email: "",
        gstin: "",
        city: "",
        area: "",
        pincode: "",
        password: "",
        confirmPassword: "",
        participateEcoPoints: false,
        receiveEcoUpdates: false,
        agreeCarbonDisclosure: false,
    },

    retailer: {
        organizationName: "",
        email: "",
        gstin: "",
        city: "",
        area: "",
        pincode: "",
        password: "",
        confirmPassword: "",
        participateEcoPoints: false,
        receiveEcoUpdates: false,
        agreeCarbonDisclosure: false,
    },

    institution: {
        organizationName: "",
        email: "",
        gstin: "",
        city: "",
        area: "",
        pincode: "",
        password: "",
        confirmPassword: "",
        participateEcoPoints: false,
        receiveEcoUpdates: false,
        agreeCarbonDisclosure: false,
    },

    college: {
        organizationName: "",
        email: "",
        gstin: "",
        city: "",
        area: "",
        pincode: "",
        password: "",
        confirmPassword: "",
        participateEcoPoints: false,
        receiveEcoUpdates: false,
        agreeCarbonDisclosure: false,
    },

    seller: {
        organizationName: "",
        email: "",
        gstin: "",
        city: "",
        area: "",
        pincode: "",
        password: "",
        confirmPassword: "",
        participateEcoPoints: false,
        receiveEcoUpdates: false,
        agreeCarbonDisclosure: false,
    }
};
